kind: Service
apiVersion: v1
metadata:
  name: hello-py-service
spec:
  selector:
    app: hello-py
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-py
  labels:
    app: hello-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-py
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: py-app
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80